name: flutter_application_1
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # ðŸ‘‡ Báº®T BUá»˜C: ThÃªm Firebase Core vÃ  Auth Ä‘á»ƒ sá»­a lá»—i
  firebase_core: ^2.27.0 
  firebase_auth: ^4.17.8
  # ðŸ‘† Káº¾T THÃšC PHáº¦N THÃŠM Má»šI

  cupertino_icons: ^1.0.2
  get: ^4.6.5
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.5
  shared_preferences: ^2.1.0
  smooth_page_indicator: ^1.1.0
  http: ^1.3.0 # âœ… ÄÃ£ sá»­a vá»‹ trÃ­ http
  cloud_firestore: ^4.17.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/